name: Battered Aggie Syndrome
favicon: null
layout_spectrum: 0.50079
typography_spectrum: 0.57666
title: Battered Aggie Syndrome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c132f'
    - '#8d3b49'
    - '#eab322'
    - '#5f9fbe'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
