name: Battered Aggie Syndrome
favicon: null
layout_spectrum: 0.36001951969228685
typography_spectrum: 0.7222556225024164
title: Battered Aggie Syndrome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#7f3b2e'
    - '#1f0e0f'
    - '#d1c2ad'
    - '#8f6a45'
  brandStrength: 0.66979492129758
  lightness: 0.17439179960638285
  saturation: 0.5857457940001041
  rhythmicContrast: 0.2598443701863289
purpose: []
