name: Battered Aggie Syndrome
favicon: null
layout_spectrum: 0.28135
typography_spectrum: 0.57666
title: Battered Aggie Syndrome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f5ec'
    - '#790414'
    - '#b9b39b'
    - '#645848'
    - '#b26551'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
