name: Battered Aggie Syndrome
favicon: null
layout_spectrum: 0.75078
typography_spectrum: 0.57666
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73738239-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f5ec'
    - '#790414'
    - '#b9b39b'
    - '#645848'
    - '#b26551'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
