name: Battered Aggie Syndrome
favicon: null
layout_spectrum: 0.80553
typography_spectrum: 0.7331
title: Battered Aggie Syndrome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f5ec'
    - '#790414'
    - '#b9b39b'
    - '#645848'
    - '#b26551'
  brandStrength: 0.66979492129758
  lightness: 0.17439179960638285
  saturation: 0.5857457940001041
  rhythmicContrast: 0.2598443701863289
purpose: []
